server {
    listen 80;
    server_name localhost;

    # Le decimos exactamente dónde están los archivos de Angular
    root /usr/share/nginx/html;
    index index.html;

    # La regla de oro para Angular: si no encuentras la ruta, manda al index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Para evitar errores con archivos estáticos
    location ~ \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        try_files $uri =404;
    }
}